# -*- coding: utf-8 -*-
"""Copy of python_data_structure_assignment_day_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pk5V0biFVN9Q3xIdkATXhee4DtN2G7ax
"""

# create empty list, name it 'a'
a = []

# print the value of a
print(a)

# print the type of a
print(type(a))

# Create a list, languages = ['R','Python', 'SAS', 'Scala', 42]
languages = ['R', 'Python', 'SAS', 'Scala', 42]

# Print the number of elements in the list
print(len(languages))

# Using for loop iterate and print all the elements in the list
for lang in languages:
    print(lang)

# Select the second item, 'Python' and store it in a new variable named 'temp'
temp = languages[1]

# Print the value of temp and type(temp)
print(temp)
print(type(temp))

# Append the element 'Java' in the list
languages.append('Java')

# Remove the element 42 from the list and print the list
languages.remove(42)
print(languages)

# Create a list, colors = ['Red', 'Blue', 'White']
colors = ['Red', 'Blue', 'White']

# Append the element 'Black' to colors
colors.append('Black')

# Append the color 'Orange' to second position (index=1) and print the list
colors.insert(1, 'Orange')
print(colors)

# Print the list
print(colors)

# Create another list, colors2 = ['Grey', 'Sky Blue']
colors2 = ['Grey', 'Sky Blue']

# Add the elements of colors2 to colors using extend function in the list
colors.extend(colors2)

# Print len of colors and its elements
print(len(colors), colors)

# Sort the list and print it.
colors.sort()
print(colors)

# Create a string, sent = 'Coronavirus Caused Lockdowns Around The World.'
sent = 'Coronavirus Caused Lockdowns Around The World.'

# Use split function to convert the string into a list of words and save it in variable words and print the same
words = sent.split()
print(words)

# Convert each word in the list to lower case and store it in variable words_lower. Print words_lower
words_lower = [word.lower() for word in words]
print(words_lower)

# Check whether 'country' is in the list
print('country' in words_lower)

# Remove the element 'the' from the list and print the list.
words_lower.remove('the')
print(words_lower)

# Select the first 4 words from the list words_lower using slicing and store them in a new variable x4
x4 = words_lower[:4]

# print x4
print(x4)

# Convert the list of elements to single string using join function and print it
print(" ".join(words_lower))

# Create stud_grades = ['A','A','B','C','C','F']
stud_grades = ['A', 'A', 'B', 'C', 'C', 'F']

# Print the len of stud_grades
print(len(stud_grades))

# Create a new variable, stud_grades_set = set(stud_grades)
stud_grades_set = set(stud_grades)

# Print stud_grades_set.
print(stud_grades_set)

# print the type of stud_grades and stud_grades_set and print their corresponding elements. Try to understand the difference between them.
print(type(stud_grades), stud_grades)
print(type(stud_grades_set), stud_grades_set)

# Add a new element 'G' to stud_grades_set
stud_grades_set.add('G')

# Add element 'F' to stud_grades_set. and print it.
stud_grades_set.add('F')
print(stud_grades_set)

# Remove 'F' from stud_grades_set
stud_grades_set.remove('F')

# Print the elements and the length of stud_grades_set
print(len(stud_grades_set), stud_grades_set)

# Create colors = ['red','blue','orange'], and fruits = ['orange','grapes','apples']
colors = ['red', 'blue', 'orange']
fruits = ['orange', 'grapes', 'apples']

# Print color and fruits
print(colors, fruits)

# Create colors_set, and fruits_set. (using set() ) and print them
colors_set = set(colors)
fruits_set = set(fruits)
print(colors_set, fruits_set)

# Find the union of both the sets.
print(colors_set.union(fruits_set))

# Find the intersection of both the sets
print(colors_set.intersection(fruits_set))

# Find the elements which are Fruits but not colors (using set.difference() )
print(fruits_set.difference(colors_set))

# Create temp = [17, 'Virat', 50.0]
temp = [17, 'Virat', 50.0]

# Iterate through temp and print all the items in temp
for item in temp:
    print(item)

# replace first element with 11 in temp
temp[0] = 11

# Set temp1 = tuple(temp)
temp1 = tuple(temp)

# Iterate through temp1 and print all the items in temp1.
for item in temp1:
    print(item)

# Create city = ("Bangalore", 28.9949521, 72)
city = ("Bangalore", 28.9949521, 72)

# Print first element of city
print(city[0])

# Create city2 = ('Chennai', 30.01, 74)
city2 = ('Chennai', 30.01, 74)

# Create cities which consist of city and city2
cities = (city, city2)

# Print cities
print(cities)

# Print type of first element in cities
print(type(cities[0]))

# print the type of cities
print(type(cities))

# Create a dictionary d = {"actor":"amir","animal":"cat","earth":2,"list":[23,32,12]}
d = {"actor": "amir", "animal": "cat", "earth": 2, "list": [23, 32, 12]}

# Store the value of d['actor'] to a new variable actor.
actor = d['actor']

# Print the type of actor
print(type(actor))

# Store the value of d['list'] in new variable List.
List = d['list']

# Print the type of List.
print(type(List))

# Create d1 = { 'singer' : 'Kr$na' , 'album': 'Still here', 'genre' : 'hip-hop'}
d1 = {'singer': 'Kr$na', 'album': 'Still here', 'genre': 'hip-hop'}

# Merge d1 into d.
d.update(d1)

# print d
print(d)

# Print all the keys in d
print(d.keys())

# Print all the values in d
print(d.values())

# Iterate over d, and print each key, value pair as this - (actor ----> amir)
for key, value in d.items():
    print(f"{key} ----> {value}")

# count the number of occurrences of characters in string named "sent" using dictionary and print the same.
char_count = {}
for char in sent:
    char_count[char] = char_count.get(char, 0) + 1
print(char_count)