# -*- coding: utf-8 -*-
"""Python Basic Assignment _2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WOEFh8G3_7ksh6YqCArz_KLYait3eTfu
"""

# Print your name using one print function
print("My name is Kunal Kulkarni")

# Define variables
mukesh = 7
z = 6
rohan = 5
longitude = 4

# Print required variable (output - 5)
print(rohan)

# Declare variables
ur_age = 21
ur_weight = 50.6
ur_first_name = 'Mukesh'
ur_last_name = "Manral"

# Print types of variables
print(type(ur_age), type(ur_weight), type(ur_first_name), type(ur_last_name))

# Print values of variables
print(ur_age, ur_weight, ur_first_name, ur_last_name)

# Compare variables
ur_first_name = 'Mukesh'
ur_last_name = 'Mukesh'
TrueOrFalse = (ur_last_name == ur_first_name)
print(TrueOrFalse)

# Define variable x and print it
x = 777
print(x)

# Initialize variables
x = 7
y = 77
z = 77.7
zz = 'Hi'

# Arithmetic operations
print(x + z)
print(z - y)
print(x * z)
print(x ** z)
print(x / z)
print(x // z)
print(x % z)

# Comparison operations
print(x < z)
print(type(x < z))
print(x <= z)
print(x == z)
print(x > z)
print(x >= z)
print(x != z)

# Logical operations
print((108 == 108) and (21 == 21))
print((108 == 108) and (21 == 11))
print((108 == 108) or (21 == 11))
print((108 == 108) or (21 == 11) or (108 <= 11))

# If-else statements
money = 100000
print(money > 2000)

money = 10000
if money > 1000:
    print("Data Science Course Free")
else:
    print("Insufficient funds")

test_score = 80
if test_score > 80:
    print("A Grade")
elif 60 < test_score <= 80:
    print("B Grade")
else:
    print("Nothing for you")

# For loop examples
for i in range(10):
    print(i)

for _ in range(10):
    print("I love sports")

# While loop example
number = 0
while number < 10:
    print(number)
    number += 1

# Break statement
for num in range(10):
    print("The number is", num)
    if num == 5:
        break

# Continue statement
for num in range(10):
    if num == 5:
        continue
    print("The number is", num)

# String manipulation
string_ = "We are creating next generation data science eco-system at CollegeRanker"
print(len(string_))
print(string_[0])
print(string_[-1])
print(string_[:6])
print(string_[7:-10])

# String functions
print(string_.count('a'))
print(string_.count('data'))
print(string_.find('data'))
print(string_.startswith('We'))
print(string_.endswith('Ranker'))
print(string_.upper())
print(string_.capitalize())
print(string_.islower())
print(string_.isupper())
print(string_.isdigit())
print(string_.isalpha())
print(string_.isalnum())

# String replace and split
new_str = "C++ is easy to learn"
print(new_str.replace("C++", "Python"))
print(new_str.split())

# Define a function
def welcome_message(name):
    print(f"Welcome {name} to Functions!!!")

welcome_message("Kunal")

# Function to add two numbers
def add_numbers(a, b):
    total = a + b
    print(total)

add_numbers(3, 4)